name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
  pull_request:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'


jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout ignition
        uses: actions/checkout@v2
        with:
          repository: spatie/ignition
          path: ignition

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v1
        with:
            working-directory: main

      - name: Run PHPStan
        run: |
            cd main
            ./vendor/bin/phpstan --error-format=github
